#!/usr/bin/with-contenv bash
# shellcheck shell=bash

WIKI_PORT="${WIKI_PORT:-8080}"
export MW_DATA_PATH="/config"

if [ -z "${LSIO_NON_ROOT_USER}" ]; then
    exec \
        s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z 127.0.0.1 ${WIKI_PORT}" \
            s6-setuidgid abc \
                php \
                    -d display_errors=Off \
                    -d error_reporting=22527 \
                    -S "0.0.0.0:${WIKI_PORT}" \
                    -t /app/mediawiki \
                    /app/mediawiki/router.php
else
    exec \
        s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z 127.0.0.1 ${WIKI_PORT}" \
            php \
                -d display_errors=Off \
                -d error_reporting=22527 \
                -S "0.0.0.0:${WIKI_PORT}" \
                -t /app/mediawiki \
                /app/mediawiki/router.php
fi
